spring:
  data:
    mongodb:
      uri: mongodb+srv://customer:Customers5@cluster0.gstcffm.mongodb.net/customersdb?retryWrites=true&w=majority&appName=Cluster0
      #port: 27017
      #database: customer_db
      #username: root
      #password: pass
      #authentication-database: admin
server:
  port: 8091
